layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  repos:
    - sudoku-solver
    - tic-tac-toe-ai
    - tic-tac-toe-reactjs
    - advent-of-code
    - http-message
    - daily-kekich-credo

skill_groups:
  - - PHP
    - Symfony
    - Ruby
    - Chef
    - C++
    - JavaScript
  - - Docker
    - Terraform
    - MySQL
    - Elasticsearch
    - Redis
    - Varnish
  - - EC2
    - Lambda
    - CloudFormation
    - RDS
    - API Gateway
    - S3

topics:
  - name: Exercise
    web_url: https://www.ensofit.co.uk
    image_url: https://tomcant.s3-eu-west-1.amazonaws.com/resources/images/ensofit-logo.png

  - name: Chess
    web_url: https://www.chess.com/member/tomcant
    image_url: https://tomcant.s3-eu-west-1.amazonaws.com/resources/images/chesscom-logo.png

  - name: Programming
    web_url: https://app.codesignal.com/profile/tomcant
    image_url: https://tomcant.s3-eu-west-1.amazonaws.com/resources/images/codesignal-logo.png
