layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: true
    forks: false
    projects:
      - tomcant.github.io
      - tideways-daemon-docker

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

skill_groups:
  - - PHP
    - Symfony
    - Ruby
    - Chef
    - C++
    - JavaScript
  - - Docker
    - Terraform
    - MySQL
    - Elasticsearch
    - Redis
    - Varnish
  - - EC2
    - Lambda
    - CloudFormation
    - RDS
    - API Gateway
    - S3

topics:
  - name: Exercise
    web_url: https://www.ensofit.co.uk
    image_url: https://tomcant.s3-eu-west-1.amazonaws.com/resources/images/ensofit-logo.png

  - name: Chess
    web_url: https://www.chess.com/member/tomcant
    image_url: https://tomcant.s3-eu-west-1.amazonaws.com/resources/images/chesscom-logo.png

  - name: Programming
    web_url: https://app.codesignal.com/profile/tomcant
    image_url: https://tomcant.s3-eu-west-1.amazonaws.com/resources/images/codesignal-logo.png
